spring:
  application:
    name: eureka-example
  cloud:
    config:
      enabled: false
# tag::configuration-eureka[]
eureka:  #<1>
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/v2/
      default: http://localhost:8080/eureka/v2/

management.security.enabled: false  #<2>
# end::configuration-eureka[]

# tag::configuration-ui-hystrix[]
spring.boot.admin.routes.endpoints: env,metrics,dump,jolokia,info,configprops,trace,refresh,heapdump,loggers,auditevents,hystrix.stream
# end::configuration-ui-hystrix[]

# tag::configuration-ui-turbine[]
spring.boot.admin.turbine:
  clusters: default
  location: turbine  #<1>
# end::configuration-ui-turbine[]

server:
  address: 0.0.0.0
  port: 8082

